/*
 Regression check for src/credit-engine.js.

 Runs the engine over the synthetic fixture (test/fixture.json, regenerated by
 test/build-fixture.js) and asserts the classification and conversion still produce
 the expected result. Fails loudly on drift.

 Expected values are derived by hand from the published per-capability rates, so a
 change in either the rate table or the classification logic is caught here rather
 than silently changing the figures the tool reports.

   node test/verify-engine.mjs
*/
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { buildRow, summarize, CC_USD } from '../src/credit-engine.js';

const here = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(here, 'fixture.json'), 'utf8'));

const all = raw.map(r => buildRow(r));
const billable = all.filter(r => !r.quicktest);
const s = summarize(billable);

/*
 Derivation, per capability: credits x (Copilot Credits / AI Builder credits).

   prompt-standard  1,240 x 1.5/24   =  77.5   (25 runs matched on model, 10 tier-assumed)
   prompt-basic       210 x 0.1/1.2  =  17.5
   prebuilt-doc       864 x 8/32     = 216
   object-detection   144 x 8/8      = 144
   custom-doc         600 x 8/100    =  48
   translation        176 x 1.5/22   =  12
   ocr                150 x 0.1/3    =   5
   simple-text         44 x 0.1/2    =   2.2
   free                 0            =   0
   unidentified         0            =   0     (reported, never costed)
                                       -----
                                       522.2
*/
const EXPECTED = {
  totalRows: 243,
  quickTests: 11,
  billableRuns: 232,
  credits: 3428,
  ccCredits: 522.2,
  usd: 5.22,
  unclassified: 7,
  capabilities: 10, // 9 identified + the unclassified bucket
  byCap: {
    'prompt-standard':  { runs: 35, credits: 1240, cc: 77.5 },
    'prompt-basic':     { runs: 50, credits: 210,  cc: 17.5 },
    'prebuilt-doc':     { runs: 27, credits: 864,  cc: 216  },
    'object-detection': { runs: 18, credits: 144,  cc: 144  },
    'custom-doc':       { runs: 6,  credits: 600,  cc: 48   },
    'translation':      { runs: 8,  credits: 176,  cc: 12   },
    'ocr':              { runs: 50, credits: 150,  cc: 5    },
    'simple-text':      { runs: 22, credits: 44,   cc: 2.2  },
    'free':             { runs: 9,  credits: 0,    cc: 0    }
  },
  byConfidence: { high: 215, medium: 10, none: 7 }
};

let ok = true;
const near = (a, b, tol = 0.01) => Math.abs(a - b) <= tol;

function check(label, got, want, tol) {
  const pass = tol === undefined ? got === want : near(got, want, tol);
  if (!pass) ok = false;
  console.log(`${pass ? 'PASS' : 'FAIL'}  ${String(label).padEnd(36)} got ${got}  want ${want}`);
}

check('rows parsed', all.length, EXPECTED.totalRows);
check('quick tests excluded', all.length - billable.length, EXPECTED.quickTests);
check('billable runs', s.runs, EXPECTED.billableRuns);
check('AI Builder credits', s.credits, EXPECTED.credits);
check('Copilot Credits', +s.ccCredits.toFixed(2), EXPECTED.ccCredits, 0.02);
check('USD at $0.01/credit', +(s.ccCredits * CC_USD).toFixed(2), EXPECTED.usd, 0.01);
check('unidentified runs', s.unclassified, EXPECTED.unclassified);
check('capability buckets', s.byCapability.length, EXPECTED.capabilities);

for (const [cap, want] of Object.entries(EXPECTED.byCap)) {
  const got = s.byCapability.find(c => c.cap === cap);
  if (!got) { ok = false; console.log(`FAIL  ${cap.padEnd(36)} capability missing from summary`); continue; }
  check(`${cap} runs`, got.runs, want.runs);
  check(`${cap} credits`, got.credits, want.credits);
  check(`${cap} Copilot Credits`, +got.cc.toFixed(2), want.cc, 0.02);
}

/* Unidentified runs must be reported and must never contribute cost. */
const unknown = s.byCapability.find(c => c.cap === '(unclassified)');
check('unidentified bucket present', Boolean(unknown), true);
check('unidentified is never costed', unknown ? unknown.cc : -1, 0);

for (const [conf, want] of Object.entries(EXPECTED.byConfidence)) {
  const got = s.byConfidence.find(c => c.conf === conf);
  check(`confidence ${conf}`, got ? got.runs : 0, want);
}

/* The per-tool view is what people act on when deciding where to optimise, so it
   must reconcile exactly with the totals rather than double counting. */
const toolTotals = s.byTool.reduce((a, t) => {
  a.runs += t.runs; a.credits += t.credits; a.cc += t.cc; return a;
}, { runs: 0, credits: 0, cc: 0 });

check('byTool runs reconcile', toolTotals.runs, s.runs);
check('byTool credits reconcile', toolTotals.credits, s.credits);
check('byTool Copilot Credits reconcile', +toolTotals.cc.toFixed(2), +s.ccCredits.toFixed(2), 0.02);
check('byTool sorted by credits', s.byTool.every((t, i, a) => i === 0 || a[i - 1].credits >= t.credits), true);
check('byTool captures language model', s.byTool.some(t => t.models.some(m => /gpt-4o/.test(m))), true);

const confRuns = s.byConfidence.reduce((n, c) => n + c.runs, 0);
check('byConfidence runs reconcile', confRuns, s.runs);
check('months present', s.byMonth.length > 1, true);

console.log('\n' + (ok
  ? 'Engine output matches the expected classification and conversion.'
  : 'ENGINE DRIFT — output no longer matches the expected figures.'));
process.exit(ok ? 0 : 1);
